name: Automated Tests and Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CI: true
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/e2e-tests/test/projects-scenarios/*/node_modules
            example/*/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}
      - name: Install node-gyp-cache
        run: |
          yarn global add node-gyp-cache
          yarn config set node_gyp node-gyp-cache
      - name: Install
        run: yarn --frozen-lockfile
      - name: Clean
        run: yarn clean
      - name: Build
        run: yarn build
      - name: lint
        run: yarn lint

  compile:
    name: Typescript compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/e2e-tests/test/projects-scenarios/*/node_modules
            example/*/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}
      - name: Install node-gyp-cache
        run: |
          yarn global add node-gyp-cache
          yarn config set node_gyp node-gyp-cache
      - name: Install
        run: yarn --frozen-lockfile
      - name: Clean
        run: yarn clean
      - name: Build tests
        run: yarn build-test

  test:
    name: Test on Linux with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/e2e-tests/test/projects-scenarios/*/node_modules
            example/*/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}
      - name: Install node-gyp-cache
        run: |
          yarn global add node-gyp-cache
          yarn config set node_gyp node-gyp-cache
      - name: Install
        run: yarn --frozen-lockfile
      - name: Clean
        run: yarn clean
      - name: Run tests
        env:
          INFURA_KEY: ${{ secrets.INFURA_KEY }}
        run: |
          yarn hardhat:node &
          sleep 10 &&
          curl http://localhost:8545 &&
          yarn test
